features/show_hide_columns.feature, features/steps/show_hide_columns.py, front_end/src/Components/ForecastTable/index.js, front_end/src/Components/Table/index.js, front_end/src/Components/TableCell/index.js, front_end/src/Reducers/ShowHideCols.js, front_end/src/index.scss
Show/hide columns in the forecast table using links at the top of the table.
=> Add full show hide logic and tests

chartofaccountDIT/templates/chartofaccountDIT/choose_year.html, chartofaccountDIT/templates/chartofaccountDIT/quick_links.html, config/settings/base.py, core/static/core/css/styles.scss, core/tables.py, core/templates/base_generic.html, core/templates/core/table_filter_generic.html, core/templates/django_tables_2_bootstrap.html, core/views.py, front_end/src/Components/Table/index.js, gifthospitality/urls.py, gifthospitality/views.py
Update chart of account styling.
=> Update chart of account style

core/static/core/css/action-bar.scss, core/static/core/css/filter.scss, core/static/core/css/styles.scss, core/static/core/css/table.scss, features/steps/show_hide_columns.py, forecast/templates/forecast/forecast_base.html, forecast/templates/forecast/view/cost_centre.html, forecast/templates/forecast/view/directorate.html, forecast/templates/forecast/view/dit.html, forecast/templates/forecast/view/group.html, forecast/views/edit_forecast.py, front_end/src/Components/EditActionBar/index.js, front_end/src/Reducers/HiddenCols.js
**Various updates to UI**
- Col widths on forecast table
- Actions bar on view forecast page
- Colour of button on view forecast page
- Width of bar on edit forecast page
=> Fix col widths in forecast table

.gitignore, costcentre/forms.py
Fix choose cost centre drop down bug
=> Attempt to fix model form bug

README.md, gifthospitality/management/commands/create_gift_hospitality_table.py, gifthospitality/management/commands/populate_gift_hospitality_table.py, gifthospitality/test/test_commands.py, makefile
Management Commands have been written to populate the tables for Gifts and Hospitality forms and search. Furthermore, Unit Tests have also been written to reflect the changes that have been made.
=> Management Commands for G and H

forecast/templates/forecast/view/cost_centre.html, forecast/templates/forecast/view/directorate.html, forecast/templates/forecast/view/dit.html, forecast/templates/forecast/view/expenditure_details/expenditure_details_base.html, forecast/templates/forecast/view/group.html, forecast/templates/forecast/view/programme_details/programme_details_base.html, forecast/views/edit_forecast.py
Remove cache for now in order to prevent lag/won't change in value update.
=> Fix edit forecast data issue when pasting values

core/static/core/css/cost-centre-filter.scss, core/static/core/css/styles.scss, forecast/templates/forecast/edit/add.html, forecast/templates/forecast/edit/choose_cost_centre.html, forecast/templates/forecast/edit/edit.html, forecast/views/edit_forecast.py, front_end/src/App.test.js, front_end/src/Apps/CostCentre.js, front_end/src/Apps/Forecast.js, front_end/src/Components/CostCentreList/index.js, front_end/src/Components/EditForecast/index.js, front_end/src/index.js
Use cost centre list and filter instead of drop down on choose cost centre page.
=> Add cost centre filter

config/settings/dev.py, config/settings/prod.py, requirements/base.txt
Add the ECS log formatter project so Kibana logs are formatted in line with expectations.
=> Add ECS log formatter

download_file/test/test_views.py, forecast/create_mi_report_source.py, forecast/test/test_download_edit_forecast.py
Check for empty values when downloading the budget report.
=> Hotfix/download budget mi (#104)

forecast/utils/query_fields.py, forecast/views/edit_forecast.py
Use the same order criteria for Edit Forecast page  and download the edit data to Excel.
=> Use the same order criteria for Edit Forecast page  and download the edit data to Excel.

costcentre/admin.py
Remove sensitive cost centre admin actions for non super users
=> Remove cost centre admin actions for non super users

gifthospitality/filters.py, gifthospitality/templates/gifthospitality/giftandhospitality_form.html
This PR is to update the Gifts and Hospitality input widths in the search section and to provide users with a GDS compliant error message for incorrect inputs to the forms.
=> Ensuring Gifts and Hospitality is GDS compliant

core/templates/base_generic.html, core/templates/core/index.html
Update index page with the correct email instructions for users so they know who to contact, also removed support link.
=> Index page email instructions

gifthospitality/management/commands/populate_gift_hospitality_table.py, gifthospitality/templates/gifthospitality/giftandhospitality_added.html, gifthospitality/templates/gifthospitality/giftandhospitality_form.html, gifthospitality/templates/gifthospitality/quick_links.html, gifthospitality/views.py
Improved formatting of form submission webpage to comply with GDS standards. Updated 'Unk' staff grade to 'Contractor'. Added relevant emails for reference in the Gift and Hospitality links page, and at the top of forms.
=> Implementing Feedback from Gift Hospitality Demonstration

gifthospitality/test/test_forms.py
Unit tests for the Gifts and Hospitality code implemented in the FFT.
=> Review of Gift and Hospitality app, writing missing unit tests.

chartofaccountDIT/templates/chartofaccountDIT/choose_year.html, chartofaccountDIT/templates/chartofaccountDIT/quick_links.html, core/templates/base_generic.html, core/templates/core/index.html, download_file/templates/download_file/downloaded_mi_reports.html, download_file/templates/download_file/downloaded_oscar_reports.html, forecast/templates/forecast/edit/add.html, forecast/templates/forecast/edit/choose_cost_centre.html, forecast/templates/forecast/edit/edit.html, forecast/templates/forecast/edit/edit_locked.html, forecast/templates/forecast/file_upload.html, forecast/templates/forecast/forecast_base.html, forecast/templates/forecast/view/cost_centre.html, forecast/templates/forecast/view/directorate.html, forecast/templates/forecast/view/dit.html, forecast/templates/forecast/view/group.html, gifthospitality/templates/gifthospitality/giftandhospitality_added.html, gifthospitality/templates/gifthospitality/giftandhospitality_form.html, gifthospitality/templates/gifthospitality/gifthospitality_filter.html, gifthospitality/templates/gifthospitality/quick_links.html, upload_file/templates/upload_file/uploaded_files.html
Updating base_generic to display appropriate title for each tab.
=> Add dynamic page titles for use with Google Analytics

core/templates/core/index.html
Gifts and Hospitality is now live so message stating Gifts and Hospitality is not in use must be removed.
=> Remove Gifts and Hospitality Disabled Message

core/templates/core/table_filter_generic.html
The tag for titles in the Chart of Account has not been picked up, this ticket is to add a relevant title.
=> Dynamic Titles Not Picked Up In CoA

core/admin.py, core/templates/core/index.html
Remove object_link references in Admin.py file in Core App to ensure Sentry compliant.
=> Fix NoneType Error on Log Entry dataset

forecast/import_actuals.py, forecast/import_budgets.py, forecast/utils/import_helpers.py
The error was caused by new field used to tag the archived data.
=> Fix error in actual upload 

.circleci/config.yml, chartofaccountDIT/test/test_admin.py, costcentre/management/commands/cost_centre_users.py, costcentre/management/commands/user_permissions.py, forecast/test/test_import_budgets.py, forecast/test/test_import_forecast.py, makefile, requirements.in/base.in, requirements.in/dev.in, requirements/base.txt, requirements/dev.txt, requirements/production.txt, setup.cfg
Use Pytest instead of Django unit test infrastructure.
=> Technical debt - implement PyTest

data_lake/test/test_natural_code.py, data_lake/views/natural_code.py
Modified test to show the bug and changed the way the field account_L6_budget_description was accessed.
=> Fixed the bug and created test for it.

download_file/templates/download_file/downloaded_mi_reports.html, download_file/test/test_views.py, download_file/views/mi_report_download.py
Show the financial year in the 'Download previous year report' button.
=> Changed the previous year download button.

config/settings/base.py, data_lake/test/test_budget_profiled_actual.py, data_lake/test/test_budget_profiled_forecast.py, data_lake/urls.py, data_lake/views/budget_profiled_actual.py, data_lake/views/budget_profiled_forecast.py
Create pipeline for profile budgets for forecast and actual periods .
This data is required in data workspace to create financial reports.
=> LST 1256 create pipeline for profiled budgets

download_file/templates/download_file/downloaded_mi_reports.html, download_file/test/test_views.py, download_file/views/mi_report_download.py, pii-ner-exclude.txt
Use a different way to call the download.
=> LST 1583: 'Download previous year MI Report' downloads the current year.

forecast/views/edit_forecast.py
When calculating the number of rows to be pasted on, only use the rows for the year to be edited .
=> LST 1620: paste full workbook failure

upload_split_file/split_actuals.py, upload_split_file/test/test_split_project.py, upload_split_file/test/test_utils.py
Corrections required for allocating the Actuals using the uploaded percentages.
=> LST 1619 upload real split percentage file

data_lake/test/test_mi_report/test_forecast_actual.py, data_lake/views/mi_report_views/forecast_actual.py, data_lake/views/mi_report_views/utils.py
Changes to avoid returning null values in queries for MI reports.
Removed field not used in queries.
=> Coalesce periodid

chartofaccountDIT/admin/archived_admin.py
Added as free field, it should be a dropdown.
Done urgently on Finance request.
=> Added Expenditure type to ADMIN for creating Archived NACs

poetry.lock
Update all minor versions of python packages with poetry
=> FFT-51 Update python packages

package-lock.json
Node packages have been audited and updated.
Only minor or patch updates should have been made.
=> FFT-52 Update node packages

front_end/src/Apps/Payroll.jsx, front_end/src/Components/EditPayroll/EmployeeRow/index.jsx, front_end/src/Components/EditPayroll/PayrollTable/index.jsx, front_end/src/Components/EditPayroll/api.js, front_end/src/Components/EditPayroll/index.jsx, front_end/src/Components/EditPayroll/types.js, payroll/services/payroll.py, payroll/templates/payroll/page/edit_payroll.html, payroll/views.py
=> FFT-86 Payroll table react components

front_end/src/Apps/Payroll.jsx, front_end/src/Components/EditPayroll/index.jsx
=> Add refresh and success message on save

forecast/templates/forecast/edit/choose_cost_centre.html, forecast/views/edit_select_cost_centre.py, front_end/src/Components/CostCentreList/index.jsx, payroll/templates/payroll/page/edit_payroll.html, payroll/urls.py
Refactor existing ChooseCostCentre component to work for edit forecast and the new edit payroll.
=> Select Cost Centre and Financial Year for Edit Payroll page

front_end/src/Components/EditPayroll/PayrollTable/index.jsx, front_end/styles/styles.scss, payroll/templates/payroll/page/edit_payroll.html
=> Fix tables overflowing on Edit Payroll

chartofaccountDIT/templates/chartofaccountDIT/choose_year.html, chartofaccountDIT/templates/chartofaccountDIT/quick_links.html, core/templates/404.html, core/templates/core/info.html, core/templates/core/table_filter_generic.html, core/templates/wide_content.html, forecast/templates/forecast/edit/choose_cost_centre.html, forecast/templates/forecast/edit/edit_locked.html, forecast/templates/forecast/edit/forecast_base.html, forecast/templates/forecast/file_upload.html, forecast/templates/forecast/view/cost_centre.html, forecast/templates/forecast/view/expenditure_details/expenditure_details_base.html, forecast/templates/forecast/view/hierarchy_base.html, forecast/templates/forecast/view/programme_details/programme_details_base.html, forecast/templates/forecast/view/project_details/project_details_base.html, upload_split_file/templates/percentage_file_upload.html
=> FF-120: Remove wide_content.html

core/templates/base_generic.html, payroll/templatetags/payroll_permissions.py, payroll/tests/test_template_tags.py
Add Edit Payroll to navigation bar
Create basic permissions file for Payroll and can_view_payroll method, currently limited to superusers
=> FFT-124: Add Edit Payroll to navigation 

.copilot/config.yml
- **Upgrade paketo buildpack**
- **fix**
=> Upgrade paketo buildpack

core/models.py
Add minimum value of 1.0 to float fields on Pay Uplift
Add maximum value of 1.0 to float fields on Attrition
=> FFT-102: Min and max validators to Pay Uplift and Attrition

config/flags.py, core/static/core/js/feature-flags.js, core/templates/base_generic.html, front_end/src/Apps/Payroll.jsx, front_end/src/Components/EditPayroll/PayrollNewTable/helpers.js, front_end/src/Components/EditPayroll/PayrollNewTable/index.jsx, front_end/styles/styles.scss, makefile, package-lock.json, package.json, payroll/templates/payroll/page/edit_payroll.html
- Add new feature flag 'payroll_new_table'
- Show new payroll table using tanstack when feature flag is active
- Table is a like-for-like replacement of existing table with the same features;
- Pay periods are checkboxes that can be toggled on / off with same functionality
- Previous months columns can be hidden
- Previous months checkboxes will be disabled if visible
=> FFT-203 Implement Tanstack for Payroll Table

front_end/src/Apps/Payroll.jsx, front_end/src/Components/EditPayroll/PayrollNewTable/columns.jsx, front_end/src/Components/EditPayroll/PayrollNewTable/helpers.js, front_end/src/Components/EditPayroll/PayrollNewTable/index.jsx
Non payroll table uses the new tanstack table implementation when the feature flag is active
It uses the same column config as Payroll, only difference is the data provided
=> FFT-221 Non Payroll table to tanstack implementation

front_end/src/Components/EditPayroll/PayrollNewTable/columns.jsx
Add existing notes column to Tanstack tables. This is added to payroll, non-payroll and vacancies
=> FFT-217 Add notes column to Tanstack tables

front_end/icons/sort-down.svg, front_end/icons/sort-up.svg, front_end/icons/unsorted.svg, front_end/src/Components/EditPayroll/PayrollNewTable/index.jsx, front_end/styles/styles.scss, package-lock.json, package.json, vite.config.js
Uses `vite-plugin-svgr` to turn svgs into useable React components
Unsorted:
Sort up:
Sort down:
=> FFT-225 Add sorting svg icons to table

core/management/commands/import_vacancy_data.py
Skip vacancy import if cost centre code, programme code or grade do not exist
=> FFT-238: Import vacancies tweaks

config/settings/base.py, core/templates/base_generic.html, front_end/styles/styles.scss, package-lock.json, package.json, poetry.lock
- **upgrade govuk-frontend**
- **upgrade vite and govuk-frontend**
- **poetry update**
=> Upgrade project dependencies

front_end/styles/styles.scss, payroll/models.py, payroll/services/payroll.py
- **upgrade govuk-frontend**
- **upgrade vite and govuk-frontend**
- **poetry update**
- **fix govuk asset refs**
- **fix**
- **fix**
- **fix**
- **fixed it**
=> FFT-260 Fix non-deterministic pay period lookups

front_end/src/Apps/Payroll.jsx, front_end/src/Components/EditPayroll/DisplayAttrition/index.jsx
Added help text for attrition
Restrict text on tabs to two thirds width
=> FFT-235 Add help text for attrition pay modifier

core/management/commands/import_vacancy_data.py
- Always create vacancies, assuming the source data has no duplicates
- Tidy up logging
=> FFT-285 Vacancy migration tweaks

core/templates/base_generic.html, core/templates/core/index.html, front_end/styles/styles.scss
Still need link for
- Learning hub
=> FFT-279 New homepage

forecast/forms.py
- Change labels to title case
- Fix NAC abbreviation to use full word
=> FFT-286 Tweaks to edit forecast add new row form

core/templates/core/index.html
- Add link for Learning Hub to homepage
- Open external links / non-FFT links in a new tab
=> Add Learning Hub link and open external links in new tabs

core/templates/403.html, core/templates/500.html
- Update error 404 page
- Add error pages for 403 and 500
TBC
=> FFT-253 Error pages for 403, 404

forecast/management/commands/new_financial_year.py, payroll/management/commands/update_payroll_forecast.py
- **wip**
- **FFT-342 Extend new financial year pre-checks**
- **Add update payroll command**
=> FFT-342 Extend new financial year pre-checks

forecast/import_actuals.py, forecast/models.py, payroll/services/payroll.py, payroll/tasks.py, payroll/tests/factories.py, payroll/tests/services/test_payroll.py
This reverts commit e2ceb5b56286e408af7196cd5516421bd311c81f.
=> Revert "FFT-318 Remove orphaned payroll forecast figures (#713)"

core/templates/core/index.html
Update dates for homepage deadlines
=> FFT-365 Update text on homepage

core/templates/core/index.html
=> FFT-368 Update homepage deadline content
