uktrade/fft

config/settings/base.py
forecast/test/test_views.py
forecast/views/edit_forecast.py
front_end/src/Components/EditActionBar/index.js
front_end/src/Components/TableCell/index.js

Set max and min amounts for forecast entry values. The max and min are configurable in settings.

Add max and min values for forecast entries

---

forecast/templatetags/forecast_format.py

Use a static list for finding month names, instead of reading them from the database.

Remove database read for each cell displayed.

---

core/static/core/css/styles.scss
forecast/templates/forecast/forecast_base.html
forecast/test/test_views.py

Visit https://fido.trade.uat.uktrade.io/forecast/edit/109003/ and the view forecast links spans the entire page width. Just the text should be linked.

View forecast Cost Centre link from Edit Forecast page is too wide

---

core/templates/base_generic.html
core/test/test_views.py
features/steps/view_admin_link.py
features/view_admin_link.feature

If users have admin access a link should be shown to the admin site. If not, the user should not be able to see a link to the admin site.

Add link from FFT site to admin site when user's have permission to access admin

---

forecast/forms.py
forecast/test/test_forms.py
forecast/test/test_views.py
forecast/views/edit_forecast.py

Amend add row logic so that it is possible to have the same NAC and programme codes for forecast rows in different cost centres.

Amend add row logic in line with Elena comments

---

features/paste_forecast_row_data.feature
features/steps/paste_actions.py
forecast/utils/edit_helpers.py
forecast/views/edit_forecast.py

When the user pasted too few columns, an uncaught exception was raised. This PR catches the exception and gives feedback to the user.

Fix too few columns pathway

---

core/templates/admin/base_site.html

Amend arrows used on Django admin group permissions control so that they are visible with accessibility software by transforming them into text.

Amend arrows on user site to be compatible with accessibility software

---

chartofaccountDIT/admin.py

Finance Administrators need to add Programme Codes, or edit existing one.
Currently, every field is read only, and there is no way to add a new one. This PR allows Finance Admins to edit the existing Programme Code description and add new Programme Codes.
This applies to full administrators too.

Programme code cannot be edited from the Admin Interface

---

gifthospitality/migrations/0004_data_20200717.py

Gifts and Hospitality does not return any records when downloaded. This is a fix to ensure G and H admins can view and download all entries.

Gifts & Hospitality download not returning any data

---

chartofaccountDIT/filters.py

Resolve error from Sentry due to extra underscore insertion: https://sentry.ci.uktrade.digital/dit/fido/issues/28283/?environment=PROD&referrer=alert_email

Sentry Error: Related Field got invalid lookup: _economic_budget_code

---

costcentre/admin.py

In the Admin interface,Finance Administrator should see the 'pencil' icon next to Cost Centre, instead of the 'eye' icon, because they can edit Cost Centres.

Icon on Admin site for Cost Centres display as pencil

---

core/admin.py
core/export_data.py
costcentre/admin.py
costcentre/forms.py
costcentre/templates/costcentre/admin/change_permission_form.html
forecast/admin.py
forecast/models.py

We need to remove all traces of user email address from the admin site. The field should no longer be surfaced anywhere.

Remove user email address from user search and cost centre user selection

---

forecast/management/commands/clear_financial_codes.py
forecast/management/commands/clear_forecast.py
forecast/test/test_clear_financial_codes.py
pii-ner-exclude.txt

Create command to delete unused financial codes.
The financial codes were not deleted at the end of the financial year, because of a bug in the deletion.
Running the new command fix the error found by the user.

LST 1606 edit forecast extra rows

---

requirements/dev.txt

Fix for 'wheel vulnerable to Regular Expression denial of service (ReDoS)', high risk vulnerability.
https://github.com/advisories/GHSA-qwmp-2cf2-g9g6

Upgraded wheel package.

---

data_lake/test/test_mi_report/test_budget.py
data_lake/views/mi_report_views/budget.py

Return all 13 periods when downloading budgets to data workspace.

Budgets returned to data workspace are not correct

---

.circleci/config.yml
config/settings/build.py
config/settings/prod.py

Currently we're seeing errors when deploying fft to a prod environment because the web svc manifest includes:
```
environments:
dev:
http:
alias: v2.fft.dev.uktrade.digital
hotfix:
http:
alias: v2.fft.hotfix.uktrade.digital
prod-data:
http:
alias: v2.fft.prod-data.uktrade.digital
prod:
http:
alias: v2.fft.trade.gov.uk
```
but the app code complains that `v2.fft.trade.gov.uk` is not listed under `ALLOWED_HOSTS`.
This change expects the fft-deploy web manifest to be updated to pass in an env var called `PROD_ALIAS.

add PROD_ALIAS to allowed hosts

---

front_end/package.json
package-lock.json
package.json

I have simplified the dependencies, but I am unable to fix the security issues.
I've managed to update `sass-loader` which fixes the `request` isuse.
I can't update `resolve-url-loader` as it's version is locked by `react-scripts`
https://github.com/facebook/create-react-app/pull/12741
I can't update `tough-cookie` as it's version is locked by `react-scripts`
https://github.com/facebook/create-react-app/issues/13285

Front End security updates

---

config/settings/paas.py
forecast/admin.py
forecast/management/commands/new_financial_year.py

Whilst trying to run the `new_finance_year` command, we ran into some bad data that had made it's way into the database. What we found was a used financial code with a NAC that had an invalid economic budget code. To resolve the issue we fixed the data by changing the NAC's economic budget code.
This commit extends the `new_finance_year` command to detect this issue before changing the financial year. It also serves to document the issue we faced.

DWPF-1767 Improve new_finance_year command

---

config/settings/base.py
core/middleware.py
core/utils/generic_helpers.py
docker-compose.yml
forecast/serialisers.py
forecast/views/edit_forecast.py
front_end/src/Util.js
package.json

I set out to improve the performance of the edit forecast page. On my local machine it took over 6 seconds just to fetch the initial HTML.
Our local dataset contains over 400 rows in the table on that page, so I suspected we had an n+1 database query problem. After some digging it turns out I was right and there were over 17,000 queries!
After a couple of days spent optimising code, mostly through the use of `select_related` and `prefetch_related`, I've managed to get the number of queries down to 13 and the page load time down to around 300ms!
Here is a brief list of the optimisations:
- apply `select_related` and `prefetch_related` where needed
- store the `current_financial_year` on the `request` object
- apply `cached_property` to view methods being used in the template
- pass the …

FFT-95 Optimise edit forecast database queries

---

core/urls.py
end_of_month/templatetags/download_permissions.py

Removed download_permissions.py for end of month as the file name clashed with an existing templatetags file and the code is no longer in use. `has_end_of_month_archive_permission` had been replaced by `has_end_of_month_archive_permissions`
Renamed report url as the colon caused an ambiguous name reference warning

Tech debt: Fix warnings

---

front_end/src/Components/EditPayroll/EditPayModifier/index.jsx
front_end/src/Components/EditPayroll/PayrollTable/index.jsx

If payroll or vacancy data is empty, display 'No data found' message, similar to Pay Modifiers tab
Fix class warning

Handle empty vacancies/payroll

---

front_end/src/Components/EditPayroll/EditPayModifier/index.jsx

Add a header to specify that the Pay Modifier is Attrition. In future, this will be dynamic based on what Pay Modifier is being displayed (Attrition / Pay Uplift)

Add header for pay modifier to specify which modifier type

---

front_end/src/Apps/Payroll.jsx
front_end/src/Components/EditPayroll/EditPayModifier/index.jsx
front_end/src/Components/EditPayroll/api.js
payroll/api.py
payroll/services/payroll.py
payroll/urls.py

If an Attrition object does not exist for a cost centre/financial year then there is a button to create one on the pay modifiers tab.

FFT-145 Create attrition object from Edit Payroll

---

core/utils/generic_helpers.py
forecast/models.py
front_end/src/Apps/Payroll.jsx
front_end/src/Components/EditPayroll/ForecastTable/index.jsx
front_end/src/Util.js
payroll/api.py
payroll/services/payroll.py

Display actuals in the forecast table in Edit Payroll. Any cell that is an actual will be grey, similar to the Forecast tables.

FFT-143 Bring actuals into Edit Payroll forecast table

---

front_end/src/Components/EditPayroll/PayrollTable/index.jsx
front_end/src/Components/EditPayroll/types.js

The logic to hide headers for previous months was using an old reference to the month name and therefore not matching on any that should be hidden

Fix previous months headers not hiding

---

.gitignore
config/urls.py
front_end/src/Components/EditForecast/index.jsx
front_end/src/Components/InfoCell/index.jsx
front_end/src/Components/TableCell/index.jsx
front_end/src/Components/TableHeader/index.jsx
front_end/src/Components/ToggleCell/index.jsx
front_end/src/Reducers/CellCount.js
front_end/src/Reducers/Cells.js
front_end/src/Reducers/Edit.js
front_end/src/Reducers/Error.js
front_end/src/Reducers/Filter.js
front_end/src/Reducers/HiddenCols.js
front_end/src/Reducers/Selected.js
front_end/src/index.jsx
front_end/styles/styles.scss
package-lock.json
package.json

FFT-175 Bumping up nodejs dependencies to latest versions  V2

---

forecast/templates/forecast/edit/edit.html
forecast/views/edit_forecast.py
front_end/src/Components/EditForecast/index.jsx
front_end/src/Components/Table/index.jsx
front_end/src/Components/TableCell/index.jsx
front_end/src/Util.js
front_end/styles/styles.scss

Remove toggle for showing payroll on Edit Forecast. This is now managed by a feature flag

FFT-173 Remove toggle from Edit Forecast and related code

---

front_end/src/Util.js

Format money to have comma as separator

FFT-208 Format money to have comma as separator

---

front_end/src/Components/EditPayroll/ForecastTable/index.jsx

Forecast table on payroll has 1an extra pound sign next to currency

Bug - Remove excess pound sign

---

front_end/src/Apps/Payroll.jsx
front_end/src/Components/EditPayroll/TanstackTable/index.jsx

The checkbox for Previous Months was not working properly.
You could only click on the label to activate the checkbox for the Payroll tab. This did not work for the Non-Payroll and Vacancies checkbox as it had the same id/ for tag as the first checkbox.
I've updated this for the search box also so that it can be differentiated by accessibility tools.
Also removed unused previous months code

Bug: Update Tanstack table to take unique table id for id fields

---

forecast/templates/forecast/edit/edit.html
front_end/src/Apps/Payroll.jsx
payroll/templates/payroll/page/edit_payroll.html

- Go to payroll / forecast links are now buttons
- Save button has new text and has moved above the tabs

FFT-207 Change go to payroll / forecast links to buttons

---

front_end/src/Apps/Payroll.jsx
front_end/src/Components/EditPayroll/DisplayAttrition/index.jsx

Attrition creation is locked off so that cost centre scoped attrition cannot be created by users.

FFT-301 Lock off attrition

---

forecast/import_actuals.py
forecast/models.py
payroll/management/commands/update_payroll_forecast.py
payroll/models.py
payroll/services/payroll.py
payroll/test_data/payroll.csv
payroll/tests/factories.py
payroll/tests/services/test_payroll.py

Orphaned payroll forecasts would occur when a financial code no being driven by the payroll forecast. This would usually happen when a vacancy was created with one programme code and then switched to another. If the first programme code was no longer used by any employee or vacancy in that cost centre, the forecast for that financial code would be left, causing the numbers to be wrong.
The solution is to remove any forecasts which are orphaned when the payroll forecast of a cost centre is updated.

FFT-318 Fix orphaned payroll forecasts
